# Application name
spring.application.name=resource-allocation

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/disaster_db
spring.datasource.username=postgres
spring.datasource.password=admin123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server port
server.port=8080
